FROM rustembedded/cross:armv7-unknown-linux-gnueabihf

RUN apt-get update \
 && apt-get install -y \
      libssl-dev \
      libmariadb-client-lgpl-dev \
      libmariadb-client-lgpl-dev-compat \
      libpq-dev

RUN dpkg --add-architecture armhf \
 && apt-get update \
 && apt-get install -y \
      libssl-dev:armhf \
      libmariadb-client-lgpl-dev:armhf \
      libmariadb-client-lgpl-dev-compat:armhf \
      libpq-dev:armhf

ENV PKG_CONFIG_ALLOW_CROSS=yes
ENV PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig
#ENV LIBRARY_PATH=/usr/lib/arm-linux-gnueabihf
#CC_armv7_unknown_linux_gnueabihf=arm-linux-gnueabihf-gcc
#ENV RUSTFLAGS="-C link-args=-L/usr/lib/arm-linux-gnueabihf"
