FROM rustembedded/cross:aarch64-unknown-linux-gnu

RUN dpkg --add-architecture arm64 \
 && apt-get update \
 && apt-get install -y \
      libssl-dev:arm64 \
      libmariadb-client-lgpl-dev:arm64 \
      libpq-dev:arm64

ENV PKG_CONFIG_ALLOW_CROSS=yes
ENV PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
#ENV LIBRARY_PATH=/usr/lib/aarch64-linux-gnu
#ENV RUSTFLAGS="-C link-args=-L/usr/lib/aarch64-linux-gnu"
